org.gradle.jvmargs=-Dfile.encoding=UTF-8

# Publishing
maven_publish.pom.name=FlowerinsnowLib
maven_publish.pom.description=flowerinsnow's lib. Whatever it is, as long as it's useful, write it.
maven_publish.pom.url=https://github.com/flowerinsnowdh/FlowerinsnowLib
maven_publish.pom.license.name=LGPL-3.0-or-later
maven_publish.pom.license.url=https://www.gnu.org/licenses/lgpl-3.0.txt
maven_publish.pom.developers.flowerinsnow.id=flowerinsnow
maven_publish.pom.developers.flowerinsnow.name=flowerinsnow
maven_publish.pom.developers.flowerinsnow.email=flowerimsnow@gmail.com
maven_publish.pom.developers.flowerinsnow.url=https://github.com/flowerinsnowdh
maven_publish.pom.developers.flowerinsnow.timezone=Asia/Shanghai
maven_publish.pom.scm.connection=scm:git:https://github.com/flowerinsnowdh/FlowerinsnowLib.git
maven_publish.pom.scm.developerConnection=scm:git:git@github.com:https://github.com/flowerinsnowdh/FlowerinsnowLib.git
maven_publish.pom.scm.tag=HEAD
maven_publish.pom.scm.url=https://github.com/flowerinsnowdh/FlowerinsnowLib
maven_publish.repo.github_packages=https://maven.pkg.github.com/flowerinsnowdh/FlowerinsnowLib
